package main

import (
	"bytes"
	"fmt"
	"html"
	"io"
	"net/http"
	"net/url"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"github.com/yuin/goldmark"
	"github.com/yuin/goldmark/ast"
	"github.com/yuin/goldmark/parser"
	"github.com/yuin/goldmark/text"
	"github.com/yuin/goldmark/util"
)

const (
	siteOrigin = "https://chaporgin.com"
	markerName = ".writings-generated"
	markerText = "generated by bin/build-writings; do not edit by hand\n"
)

var (
	dateRe    = regexp.MustCompile(`^\d{4}-\d{2}-\d{2}$`)
	slugRe    = regexp.MustCompile(`^[a-z0-9]+(?:-[a-z0-9]+)*$`)
	firstH1Re = regexp.MustCompile(`^#[ \t]+\S`)

	allowedExts = map[string]bool{".jpg": true, ".jpeg": true, ".png": true, ".pdf": true}
)

// Config holds the filesystem roots the generator operates on.
type Config struct {
	ContentRoot string // content/writings
	OutputRoot  string // public
	SiteDir     string // site (static files copied verbatim into OutputRoot)
}

// Article is one parsed, validated source article.
type Article struct {
	Date        string
	Slug        string
	Title       string
	BodyHTML    string
	Attachments []string
	SourceDir   string
	Route       string
}

func newMarkdown() goldmark.Markdown {
	// goldmark defaults: CommonMark, raw HTML disabled (omitted from output).
	// The AST transformer gives every content paragraph a stable, unique id
	// (p1, p2, ...) so each paragraph is directly linkable via #pN.
	return goldmark.New(
		goldmark.WithParserOptions(
			parser.WithASTTransformers(
				util.Prioritized(paragraphIDTransformer{}, 100),
			),
		),
	)
}

// paragraphIDTransformer assigns each paragraph a sequential id in document
// order. Numbering is deterministic, so identical sources produce identical ids.
type paragraphIDTransformer struct{}

func (paragraphIDTransformer) Transform(doc *ast.Document, _ text.Reader, _ parser.Context) {
	n := 0
	_ = ast.Walk(doc, func(node ast.Node, entering bool) (ast.WalkStatus, error) {
		if !entering {
			return ast.WalkContinue, nil
		}
		if _, ok := node.(*ast.Paragraph); ok {
			n++
			node.SetAttributeString("id", []byte(fmt.Sprintf("p%d", n)))
		}
		return ast.WalkContinue, nil
	})
}

func isValidDate(s string) bool {
	if !dateRe.MatchString(s) {
		return false
	}
	t, err := time.Parse("2006-01-02", s)
	return err == nil && t.Format("2006-01-02") == s
}

func slugify(title string) string {
	var b strings.Builder
	pendingHyphen := false
	for _, r := range strings.ToLower(title) {
		if (r >= 'a' && r <= 'z') || (r >= '0' && r <= '9') {
			if pendingHyphen && b.Len() > 0 {
				b.WriteByte('-')
			}
			pendingHyphen = false
			b.WriteRune(r)
		} else {
			pendingHyphen = true
		}
	}
	s := strings.Trim(b.String(), "-")
	if s == "" {
		return "note"
	}
	return s
}

// validateReference checks a link href or image src found in article
// Markdown. It returns the attachment filename when the reference points
// into the article's own files/ directory, otherwise "".
func validateReference(raw, articleDir, srcPath string) (string, error) {
	ref := strings.TrimSpace(raw)
	decoded := ref
	if d, err := url.PathUnescape(ref); err == nil {
		decoded = d
	}
	low := strings.ToLower(decoded)
	bad := func(reason string) (string, error) {
		return "", fmt.Errorf("%s: reference %q rejected: %s", srcPath, raw, reason)
	}
	if strings.Contains(decoded, `\`) {
		return bad("backslash-based paths are not allowed")
	}
	for _, scheme := range []string{"javascript:", "data:", "file:", "vbscript:"} {
		if strings.HasPrefix(low, scheme) {
			return bad(scheme + " URLs are not allowed")
		}
	}
	rawLow := strings.ToLower(ref)
	if strings.HasPrefix(rawLow, "http://") || strings.HasPrefix(rawLow, "https://") ||
		strings.HasPrefix(rawLow, "mailto:") {
		return "", nil // ordinary external link
	}
	if strings.HasPrefix(ref, "#") {
		return "", nil
	}
	if strings.HasPrefix(ref, "//") {
		return bad("protocol-relative URLs are not allowed")
	}
	if strings.Contains(decoded, "..") {
		return bad("path traversal ('..') is not allowed")
	}
	if strings.HasPrefix(ref, "/") {
		return "", nil // root-relative internal link, e.g. /writings
	}
	if strings.HasPrefix(decoded, "files/") {
		name := decoded[len("files/"):]
		if name == "" || strings.Contains(name, "/") {
			return bad("attachment references must point directly into this article's files directory")
		}
		if strings.HasPrefix(name, ".") {
			return bad("hidden files are not allowed")
		}
		ext := strings.ToLower(filepath.Ext(name))
		if !allowedExts[ext] {
			return bad("attachment type " + ext + " is not allowed; only .jpg, .jpeg, .png and .pdf are supported")
		}
		target := filepath.Join(articleDir, "files", name)
		fi, err := os.Lstat(target)
		if err != nil {
			return bad("referenced attachment does not exist")
		}
		if fi.Mode()&os.ModeSymlink != 0 {
			return bad("attachment is a symbolic link")
		}
		if !fi.Mode().IsRegular() {
			return bad("attachment is not a regular file")
		}
		return name, nil
	}
	return bad("relative references must start with 'files/'; external links must use http(s)")
}

func collectAttachments(articleDir string) ([]string, error) {
	filesDir := filepath.Join(articleDir, "files")
	fi, err := os.Lstat(filesDir)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, nil
		}
		return nil, err
	}
	if fi.Mode()&os.ModeSymlink != 0 {
		return nil, fmt.Errorf("%s: 'files' must not be a symlink", filesDir)
	}
	if !fi.IsDir() {
		return nil, fmt.Errorf("%s: 'files' must be a directory", filesDir)
	}
	entries, err := os.ReadDir(filesDir)
	if err != nil {
		return nil, err
	}
	var names []string
	for _, de := range entries {
		name := de.Name()
		p := filepath.Join(filesDir, name)
		if strings.HasPrefix(name, ".") {
			return nil, fmt.Errorf("%s: hidden files are not allowed in attachment directories", p)
		}
		if de.Type()&os.ModeSymlink != 0 {
			return nil, fmt.Errorf("%s: symbolic links are not allowed", p)
		}
		if !de.Type().IsRegular() {
			return nil, fmt.Errorf("%s: only regular files are allowed in attachment directories", p)
		}
		ext := strings.ToLower(filepath.Ext(name))
		if !allowedExts[ext] {
			return nil, fmt.Errorf("%s: attachment type %q is not supported; only .jpg, .jpeg, .png and .pdf are allowed", p, ext)
		}
		names = append(names, name)
	}
	return names, nil
}

func headingRawText(h *ast.Heading, source []byte) string {
	var parts []string
	lines := h.Lines()
	for i := 0; i < lines.Len(); i++ {
		seg := lines.At(i)
		parts = append(parts, string(seg.Value(source)))
	}
	return strings.TrimSpace(strings.Join(parts, " "))
}

func parseArticle(md goldmark.Markdown, dir, date, slug string) (*Article, error) {
	srcPath := filepath.Join(dir, "index.md")
	fi, err := os.Lstat(srcPath)
	if err != nil {
		return nil, fmt.Errorf("%s: missing index.md", dir)
	}
	if fi.Mode()&os.ModeSymlink != 0 {
		return nil, fmt.Errorf("%s: index.md must not be a symlink", dir)
	}
	source, err := os.ReadFile(srcPath)
	if err != nil {
		return nil, fmt.Errorf("%s: %v", srcPath, err)
	}
	if !utf8.Valid(source) {
		return nil, fmt.Errorf("%s: file is not valid UTF-8", srcPath)
	}

	firstLine := ""
	for _, line := range strings.Split(string(source), "\n") {
		if strings.TrimSpace(line) != "" {
			firstLine = strings.TrimRight(line, "\r")
			break
		}
	}
	if firstLine == "" {
		return nil, fmt.Errorf("%s: article is empty; the first non-empty line must be a single '# Title' heading", srcPath)
	}
	if !firstH1Re.MatchString(firstLine) {
		return nil, fmt.Errorf("%s: the first non-empty line must be exactly one level-one Markdown heading ('# Title'); found %q", srcPath, firstLine)
	}

	doc := md.Parser().Parse(text.NewReader(source))

	h1Count := 0
	var titleNode *ast.Heading
	_ = ast.Walk(doc, func(n ast.Node, entering bool) (ast.WalkStatus, error) {
		if !entering {
			return ast.WalkContinue, nil
		}
		if h, ok := n.(*ast.Heading); ok && h.Level == 1 {
			h1Count++
			if titleNode == nil {
				titleNode = h
			}
		}
		return ast.WalkContinue, nil
	})
	if h1Count == 0 || titleNode == nil {
		return nil, fmt.Errorf("%s: no level-one heading found", srcPath)
	}
	if h1Count > 1 {
		return nil, fmt.Errorf("%s: multiple level-one headings found; only the title may be a level-one heading", srcPath)
	}
	if doc.FirstChild() != ast.Node(titleNode) {
		return nil, fmt.Errorf("%s: the level-one heading must be the first content", srcPath)
	}
	title := headingRawText(titleNode, source)
	if title == "" {
		return nil, fmt.Errorf("%s: article title is empty", srcPath)
	}

	var walkErr error
	_ = ast.Walk(doc, func(n ast.Node, entering bool) (ast.WalkStatus, error) {
		if !entering {
			return ast.WalkContinue, nil
		}
		var dest string
		switch v := n.(type) {
		case *ast.Link:
			dest = string(v.Destination)
		case *ast.Image:
			dest = string(v.Destination)
		case *ast.AutoLink:
			dest = string(v.URL(source))
		default:
			return ast.WalkContinue, nil
		}
		if _, err := validateReference(dest, dir, srcPath); err != nil {
			walkErr = err
			return ast.WalkStop, nil
		}
		return ast.WalkContinue, nil
	})
	if walkErr != nil {
		return nil, walkErr
	}

	attachments, err := collectAttachments(dir)
	if err != nil {
		return nil, err
	}

	doc.RemoveChild(doc, titleNode)
	var buf bytes.Buffer
	if err := md.Renderer().Render(&buf, source, doc); err != nil {
		return nil, fmt.Errorf("%s: rendering failed: %v", srcPath, err)
	}

	return &Article{
		Date:        date,
		Slug:        slug,
		Title:       title,
		BodyHTML:    buf.String(),
		Attachments: attachments,
		SourceDir:   dir,
		Route:       "/writings/" + date + "/" + slug + "/",
	}, nil
}

func discoverArticles(cfg Config, md goldmark.Markdown) ([]*Article, error) {
	var articles []*Article
	entries, err := os.ReadDir(cfg.ContentRoot)
	if err != nil {
		if os.IsNotExist(err) {
			return articles, nil
		}
		return nil, err
	}
	routes := map[string]string{}
	for _, de := range entries {
		name := de.Name()
		if strings.HasPrefix(name, ".") {
			continue
		}
		p := filepath.Join(cfg.ContentRoot, name)
		if de.Type()&os.ModeSymlink != 0 {
			return nil, fmt.Errorf("%s: symbolic links are not allowed", p)
		}
		if !de.IsDir() {
			return nil, fmt.Errorf("%s: unexpected file; only YYYY-MM-DD directories are allowed here", p)
		}
		if !dateRe.MatchString(name) {
			return nil, fmt.Errorf("%s: directory name %q is not a valid YYYY-MM-DD date", p, name)
		}
		if !isValidDate(name) {
			return nil, fmt.Errorf("%s: %q is not a real calendar date", p, name)
		}
		slugEntries, err := os.ReadDir(p)
		if err != nil {
			return nil, err
		}
		for _, se := range slugEntries {
			slug := se.Name()
			if strings.HasPrefix(slug, ".") {
				continue
			}
			sp := filepath.Join(p, slug)
			if se.Type()&os.ModeSymlink != 0 {
				return nil, fmt.Errorf("%s: symbolic links are not allowed", sp)
			}
			if !se.IsDir() {
				return nil, fmt.Errorf("%s: unexpected file; only article slug directories are allowed here", sp)
			}
			if !slugRe.MatchString(slug) {
				return nil, fmt.Errorf("%s: slug %q is invalid; slugs must match ^[a-z0-9]+(?:-[a-z0-9]+)*$", sp, slug)
			}
			inner, err := os.ReadDir(sp)
			if err != nil {
				return nil, err
			}
			for _, ie := range inner {
				n := ie.Name()
				if strings.HasPrefix(n, ".") {
					continue
				}
				if n != "index.md" && n != "files" {
					return nil, fmt.Errorf("%s: unexpected entry; an article directory may contain only index.md and files/", filepath.Join(sp, n))
				}
			}
			a, err := parseArticle(md, sp, name, slug)
			if err != nil {
				return nil, err
			}
			if prev, ok := routes[a.Route]; ok {
				return nil, fmt.Errorf("%s: output route %s conflicts with %s", sp, a.Route, prev)
			}
			routes[a.Route] = sp
			articles = append(articles, a)
		}
	}
	sort.Slice(articles, func(i, j int) bool {
		if articles[i].Date != articles[j].Date {
			return articles[i].Date > articles[j].Date // date descending
		}
		return articles[i].Slug < articles[j].Slug // slug ascending
	})
	return articles, nil
}

func esc(s string) string { return html.EscapeString(s) }

func pageShell(title, canonicalPath, body string) string {
	return "<!doctype html>\n" +
		"<html lang=\"en\">\n" +
		"<head>\n" +
		"  <meta charset=\"utf-8\">\n" +
		"  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n" +
		"  <title>" + esc(title) + "</title>\n" +
		"  <link rel=\"canonical\" href=\"" + esc(siteOrigin+canonicalPath) + "\">\n" +
		"  <link rel=\"icon\" href=\"/favicon.ico\" sizes=\"any\">\n" +
		"  <link rel=\"icon\" href=\"/favicon.svg\" type=\"image/svg+xml\">\n" +
		"  <style>img{max-width:1000px;height:auto}</style>\n" +
		"</head>\n" +
		"<body>\n" +
		body +
		"</body>\n" +
		"</html>\n"
}

func renderIndex(articles []*Article) string {
	var items strings.Builder
	for _, a := range articles {
		items.WriteString("  <li>" + a.Date + " - <a href=\"" + esc(a.Route) + "\">" + esc(a.Title) + "</a></li>\n")
	}
	body := "<h1>Writings</h1>\n<ul>\n" + items.String() + "</ul>\n"
	return pageShell("Writings", "/writings/", body)
}

func renderArticle(a *Article) string {
	body := "<p><a href=\"/writings/\">Writings</a></p>\n" +
		"<article>\n" +
		"<h1>" + esc(a.Title) + "</h1>\n" +
		"<p>" + a.Date + "</p>\n" +
		a.BodyHTML +
		"</article>\n"
	return pageShell(a.Title, a.Route, body)
}

func writeTextFile(path, content string) error {
	return os.WriteFile(path, []byte(content), 0o644)
}

func copyFile(src, dst string) error {
	in, err := os.Open(src)
	if err != nil {
		return err
	}
	defer in.Close()
	out, err := os.OpenFile(dst, os.O_WRONLY|os.O_CREATE|os.O_TRUNC, 0o644)
	if err != nil {
		return err
	}
	if _, err := io.Copy(out, in); err != nil {
		out.Close()
		return err
	}
	return out.Close()
}

// runBuild validates every article, builds the complete output in a
// temporary directory, and only then swaps it into public/writings.
// It refuses to delete a public/writings directory it does not own.
func runBuild(cfg Config) ([]*Article, error) {
	md := newMarkdown()
	articles, err := discoverArticles(cfg, md)
	if err != nil {
		return nil, err
	}
	if err := os.MkdirAll(cfg.OutputRoot, 0o755); err != nil {
		return nil, err
	}
	tmp, err := os.MkdirTemp(cfg.OutputRoot, ".writings-build-")
	if err != nil {
		return nil, err
	}
	defer os.RemoveAll(tmp)

	wtmp := filepath.Join(tmp, "writings")
	if err := os.MkdirAll(wtmp, 0o755); err != nil {
		return nil, err
	}
	if err := writeTextFile(filepath.Join(wtmp, markerName), markerText); err != nil {
		return nil, err
	}
	if err := writeTextFile(filepath.Join(wtmp, "index.html"), renderIndex(articles)); err != nil {
		return nil, err
	}
	for _, a := range articles {
		outDir := filepath.Join(wtmp, a.Date, a.Slug)
		if err := os.MkdirAll(outDir, 0o755); err != nil {
			return nil, err
		}
		if err := writeTextFile(filepath.Join(outDir, "index.html"), renderArticle(a)); err != nil {
			return nil, err
		}
		if len(a.Attachments) > 0 {
			filesOut := filepath.Join(outDir, "files")
			if err := os.MkdirAll(filesOut, 0o755); err != nil {
				return nil, err
			}
			for _, name := range a.Attachments {
				if err := copyFile(filepath.Join(a.SourceDir, "files", name), filepath.Join(filesOut, name)); err != nil {
					return nil, err
				}
			}
		}
	}

	target := filepath.Join(cfg.OutputRoot, "writings")
	if fi, err := os.Lstat(target); err == nil {
		switch {
		case fi.IsDir():
			if _, merr := os.Stat(filepath.Join(target, markerName)); merr == nil {
				if err := os.RemoveAll(target); err != nil {
					return nil, err
				}
			} else if entries, rerr := os.ReadDir(target); rerr == nil && len(entries) == 0 {
				if err := os.Remove(target); err != nil {
					return nil, err
				}
			} else {
				return nil, fmt.Errorf("%s: refusing to replace this path; it was not generated by bin/build-writings (missing %s marker)", target, markerName)
			}
		default:
			return nil, fmt.Errorf("%s: refusing to replace this path; it is not a directory generated by bin/build-writings", target)
		}
	}
	if err := os.Rename(wtmp, target); err != nil {
		return nil, err
	}

	if cfg.SiteDir != "" {
		if entries, err := os.ReadDir(cfg.SiteDir); err == nil {
			for _, de := range entries {
				if de.Type().IsRegular() && !strings.HasPrefix(de.Name(), ".") {
					if err := copyFile(filepath.Join(cfg.SiteDir, de.Name()), filepath.Join(cfg.OutputRoot, de.Name())); err != nil {
						return nil, err
					}
				}
			}
		}
	}
	return articles, nil
}

func runNew(cfg Config, title, date, slug string) (indexPath, filesDir string, err error) {
	title = strings.TrimSpace(title)
	if title == "" {
		return "", "", fmt.Errorf("title must not be empty")
	}
	if date == "" {
		date = time.Now().Format("2006-01-02")
	} else if !isValidDate(date) {
		return "", "", fmt.Errorf("--date %q is not a valid YYYY-MM-DD calendar date", date)
	}
	if slug == "" {
		slug = slugify(title)
	} else if !slugRe.MatchString(slug) {
		return "", "", fmt.Errorf("--slug %q is invalid; slugs must match ^[a-z0-9]+(?:-[a-z0-9]+)*$", slug)
	}
	dir := filepath.Join(cfg.ContentRoot, date, slug)
	if _, lerr := os.Lstat(dir); lerr == nil {
		return "", "", fmt.Errorf("%s: article already exists; refusing to overwrite", dir)
	}
	filesDir = filepath.Join(dir, "files")
	if err := os.MkdirAll(filesDir, 0o755); err != nil {
		return "", "", err
	}
	indexPath = filepath.Join(dir, "index.md")
	if err := os.WriteFile(indexPath, []byte("# "+title+"\n\n"), 0o644); err != nil {
		return "", "", err
	}
	return indexPath, filesDir, nil
}

func cmdPreview(cfg Config, args []string) error {
	port := os.Getenv("PORT")
	if port == "" {
		port = "8000"
	}
	for i := 0; i < len(args); i++ {
		if args[i] == "--port" && i+1 < len(args) {
			port = args[i+1]
			i++
		}
	}
	if _, err := runBuild(cfg); err != nil {
		return err
	}
	addr := "127.0.0.1:" + port
	fmt.Println("Serving " + cfg.OutputRoot)
	fmt.Println("Writings: http://" + addr + "/writings/")
	return http.ListenAndServe(addr, http.FileServer(http.Dir(cfg.OutputRoot)))
}
